### ISSUE TITLE
Utiliser ODbL comme licence ?

### ISSUE THREAD

**Issue by fmassot** [depuis1958/sondages#1]
C'est l'équivalent de l'AGPL pour les données, c'est le choix par exemple d'OSM expliqué ici http://www.openstreetmap.fr/openstreetmap-odbl

ODbL : https://fr.wikipedia.org/wiki/Open_Database_License

**Comment by victorpoughon** [comment]
c'est quoi le problème avec CC BY-NC ?

**Comment by fmassot** [comment]
L'aspect non commercial NC est souvent jugé trop flou : https://scinfolex.com/2017/03/08/quand-la-clause-non-commercial-des-licences-creative-commons-passe-en-justice/

L'ODbL est taillée pour les bases de données et inclut une clause de share alike, c'est pour ça que cette licence est intéressante si on ne souhaite pas que qqn d'autre se réapproprie les données sans contribuer.

c'est juste une suggestion :)

**Comment by victorpoughon** [comment]
merci pour les remarques c'est intéressant. J'ai pas trouvé de texte en français pour OBdL donc j'ai changé pour CC BY-SA. Ca me parait mieux en effet.
