### ISSUE TITLE
durée d'intégration des sondages

### ISSUE THREAD

**Issue by TomBugnon** [depuis1958/sondages#17]
Bonjour !
Si je comprends bien les estimations proposées intègrent tous les sondages depuis janvier. Serait il possible d'estimer les chances d'accéder au premier tour en intégrant les sondages des dernières eg 2 semaines uniquement? Et ainsi de prendre un peu en compte les dynamiques de derniere minute. 
Je serais curieux de voir si Mélenchon est toujours à 2% dans ce cas. Merci!
Tom

**Comment by victorpoughon** [comment]
Salut

Alors en effet tu met le doigt sur une caractéristique ce ce modèle. Mais c'est un peu plus compliqué que ça. En fait, tout les sondages depuis le 01/01 sont pris en compte (c'est une date arbitraire) mais avec une pondération (via les coefficients de Dirichlet) qui dépend de leur distance au jour du vote qu'ils estiment. De plus, seul le dernier sondage de chaque institut est considéré. C'est à dire que concrètement pour l'estimation actuelle, aucun sondage plus ancien que le 2 Avril ne rentre dans l'estimation (çà correspond au dernier Cevipof-Ipsos).

L'autre conséquence c'est que la courbe n'avance pas si aucun sondage ne sort. Ce qui visuellement est moins satisfaisant que si elle avançait en temps réel.

C'est un choix qu'on peut tout à fait remettre en question du coup. Bon je vais pas changer le modèle à 2 semaine du premier tour ce serait un peu de la triche :) Mais en effet vu les changements importants qu'on observe cette année ça pourrait être intéressant d'avoir un modèle plus réactif. L'inconvénient de cette modification ce serait que lors d'une période avec peu de sondages, les probabilités se recentreraient lentement vers une distribution uniforme. Mais vu la fréquence de malade des sondeurs c'est pas forcement un souci.
