### ISSUE TITLE
Proposer 1 méthodo pour compléter le dataset

### ISSUE THREAD

**Issue by fmassot** [depuis1958/sondages#2]
Afin d'avoir une vision de ce qui est en cours de collecte, on pourrait par exemple créer une issue "collecte sondage XXX", qqn s'affecte dessus s'il fait le boulot et fait une PR.

je propose ça juste parce que ça me fait toujours mal de m'apercevoir que j'ai fait un boulot "un peu débile" pour rien :)

**Comment by victorpoughon** [comment]
Ca c'est un problème que j'aimerai bien avoir :)
Si tu veux annoncer que tu es en train de collecter un sondage tu peux faire une issue pour l'année correspondante par exemple. Pour 2017 c'est au compte goutte de toute façon.
